StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{612B167AE86E1F6C}" {
   Id "SK_CAR_UAZ469_Police"
   Target_en_us "UAZ469 Police"
   Target_pl_pl "UAZ469 Milicja"
   Status DEVELOPMENT_DONE
   Modified 1630214122
   Author "Milosz"
   LastChanged "Milosz"
  }
  CustomStringTableItem "{612B167AEF280653}" {
   Id "SK_CAR_UAZ469_Police_Blue"
   Target_en_us "UAZ469 Police Blue"
   Target_pl_pl "UAZ469 Milicja Niebieski"
   Modified 1630214114
   Author "Milosz"
   LastChanged "Milosz"
  }
 }
}