SCR_MapMarkerConfig {
 m_aMarkerEntryConfigs {
  SK_MapMarkerEntryUnit "{66C4B41604F7323C}" {
   m_sMarkerLayout "{0028B80399C07B00}UI/layouts/AirSupport/MapUnitAreaFrame.layout"
   m_sMarkerPrefab "{54796A950029BA4A}Prefabs/Markers/MapMarkerUnit.et"
  }
 }
}