SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  SK_GameStateSystem "{685D4E00155BF7A8}" {
   SystemLocation Server
  }
  SK_CivilianSpawnSystem "{685D4E01F0A21201}" {
   SystemLocation Server
  }
  SK_CivilianMovementSystem "{68612B399387436C}" {
   SystemLocation Server
  }
 }
}