SCR_PlaceableEntitiesRegistry {
 m_sAddon "ArmaReforger"
 m_sSourceDirectory "{F9291FCE0C1F7605}Prefabs/Vehicles"
 m_bExposed 1
 m_Prefabs {
  "{647B628D3671841D}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_Militia.et"
  "{3D3B2730DD5CD4E7}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_Militia_Blue.et"
 }
}